version: 2
updates:
# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Open update PRs in groups rather than one-by-one
    groups:
      actions:
        patterns:
          - "*"
